# ======================================================
# APP
# ======================================================
spring.application.name=CarburoAPI

# ======================================================
# Configuración HTTP - SERVER
# ======================================================
server.port=8089
server.forward-headers-strategy=framework

# ======================================================
# Configuración de la BD PostgreSQL
# ======================================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

# ======================================================
# JPA/Hibernate
# ======================================================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# ======================================================
# LOGGING
# ======================================================
logging.level.org.hibernate=ERROR
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF
logging.level.org.hibernate.orm.connections.pooling=ERROR

logging.level.org.springframework.web=DEBUG

# =========================
# API BASE PATH
# =========================
server.servlet.context-path=/api

# =========================
# JSON
# =========================
spring.jackson.serialization.indent_output=true
spring.jackson.default-property-inclusion=non_null

# =========================
# SECURITY (CUSTOM)
# =========================
security.api.key=${PUBLIC_API_KEY}

# Supabase
security.jwt.issuer=${SUPABASE_ISSUER}
security.jwt.jwks-url=${SUPABASE_JWKS_URL}