# ======================================================
# APP
# ======================================================
spring.application.name=CarburoAPI

# ======================================================
# Configuración HTTP - SERVER
# ======================================================
server.port=8089
server.forward-headers-strategy=framework

server.compression.enabled=true
server.compression.mime-types=application/json,application/xml,text/html,text/plain
server.compression.min-response-size=1024

# ======================================================
# Status/Health - Actuator
# ======================================================
management.endpoints.web.base-path=/public/status
management.endpoints.web.exposure.include=health, info
management.info.build.enabled=true
management.info.env.enabled=true
info.app.name=Carburo App
info.app.url=https://carburo.app
info.api.name=Carburo API REST
info.api.url=https://api.carburo.app
info.version=@project.version@
info.api.description=@project.description@
management.endpoint.health.show-details=never
management.endpoint.health.show-components=always

# ======================================================
# Configuración de la BD PostgreSQL
# ======================================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

# ======================================================
# JPA/Hibernate
# ======================================================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=true

# ======================================================
# LOGGING
# ======================================================
logging.level.org.hibernate=ERROR
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF
logging.level.org.hibernate.orm.connections.pooling=ERROR

# =========================
# API BASE PATH
# =========================
server.servlet.context-path=/api

# =========================
# JSON
# =========================
spring.jackson.serialization.indent_output=true
spring.jackson.default-property-inclusion=non_null

# =========================
# SECURITY (CUSTOM)
# =========================
security.api.key=${PUBLIC_API_KEY}

# Supabase
security.jwt.issuer=${SUPABASE_ISSUER}
security.jwt.jwks-url=${SUPABASE_JWKS_URL}

# =========================
# CACHE
# =========================
spring.cache.type=caffeine
spring.cache.cache-names=dtos_grupo_combustibles,dtos_combustibles,entities_grupo_combustibles,entities_combustibles,grupo_combustibles,ccaa,provincias,municipios,municipiosConEESS,eess_count,combustibles_analiticas_hoy
spring.cache.caffeine.spec=maximumSize=1000,expireAfterWrite=12h,recordStats